### ISSUE TITLE
Unable to get widgets

### ISSUE THREAD

**Issue by ghost** [dustyf/acf-widget-area#4]
Hi this looks a really promising add on to ACF.

I'm having some issues getting it to work. The following code doesn't seem to do anything. Any ideas on what I'm doing wrong?

<?php if( have_rows('footer_widgets', 'options') ):

  while(has_sub_field('footer_widgets', 'option')): ?>

```
    <li><?php the_sub_field('widget'); ?></li>
```

<?php endwhile; 

endif; ?>

**Comment by dustyf** [comment]
I have now fixed this to work with ACF Repeater Field
